apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
        - name: wisecow-container
          image: wisecow:v3
---
apiVersion: v1
kind: Service
metadata:
  name: wisecow-svc
spec:
  selector:
    app: wisecow
  ports:
    - protocol: TCP
      port: 4499
      targetPort: 4499
  type: NodePort