# .github/workflows/docker-build-push.yml
name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Adjust to your branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build -t localhost:5000/wisecow:latest .

    - name: Push Docker image to local registry
      run: |
        docker push localhost:5000/wisecow:latest

    - name: Configure kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Deploy to Minikube
      env:
        KUBECONFIG: ${{ secrets.kubeconfig }}
      run: |
        kubectl apply -f wisecow-manifest.yaml